# Generated by Django 2.0.5 on 2018-05-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0002_auto_20180514_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='altitudine',
            new_name='latitudine',
        ),
    ]
