# Generated by Django 2.0.5 on 2018-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0003_auto_20180514_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
