# Generated by Django 2.0.5 on 2018-05-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0004_intervento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='thumb_intervento',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
