# Generated by Django 2.0.5 on 2018-05-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0005_intervento_thumb_intervento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='created_date',
            new_name='anno',
        ),
    ]
