# Generated by Django 2.0.5 on 2018-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0006_auto_20180515_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='commercializzazione',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='committente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='fine_lavori',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='impianti',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='impresa',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='inizio_lavori',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='progetto_del_verde',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='sito_intervanto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='strutture',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='url_committente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intervento',
            name='video',
            field=models.CharField(default='', max_length=200),
        ),
    ]
