# Generated by Django 2.0.5 on 2018-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0007_auto_20180515_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='descrizione',
            field=models.TextField(default=''),
        ),
    ]
