# Generated by Django 2.0.5 on 2018-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0008_intervento_descrizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
