# Generated by Django 2.0.5 on 2018-05-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0011_auto_20180515_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='', upload_to='')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interventi.Intervento')),
            ],
        ),
    ]
