# Generated by Django 2.0.5 on 2018-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0013_auto_20180515_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_project',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
