# Generated by Django 2.0.5 on 2018-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0014_photo_project_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_project',
            name='titolo_photo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
