# Generated by Django 2.0.5 on 2018-05-15 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0015_photo_project_titolo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='anno',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='commercializzazione',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='committente',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='descrizione',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='fine_lavori',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='impianti',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='impresa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='inizio_lavori',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='progetto_del_verde',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='sito_intervanto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='strutture',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='url_committente',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='video',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
