# Generated by Django 2.0.5 on 2018-05-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0018_intervento_photo_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo_project',
            new_name='photo',
        ),
    ]
