# Generated by Django 2.0.5 on 2018-05-15 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0019_auto_20180515_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
