# Generated by Django 2.0.5 on 2018-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0021_intervento_info_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='thumb_active',
            field=models.BooleanField(default=False, help_text='If is checked show the Thumb Project', verbose_name='Attiva Thumb Project'),
        ),
    ]
