# Generated by Django 2.0.5 on 2018-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0022_intervento_thumb_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='video_active',
            field=models.BooleanField(default=False, help_text='If is checked show the Video Project', verbose_name='Attiva Video Project'),
        ),
    ]
