# Generated by Django 2.0.5 on 2018-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0024_auto_20180515_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='commercializzazione_active',
            field=models.BooleanField(default=False, help_text='If is checked show the commercializzazione', verbose_name='Attiva commercializzazione'),
        ),
    ]
