# Generated by Django 2.0.5 on 2018-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0025_intervento_commercializzazione_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='sito_intervanto',
            new_name='sito_intervento',
        ),
        migrations.AddField(
            model_name='intervento',
            name='sito_intervento_active',
            field=models.BooleanField(default=False, help_text='If is checked show sito intervento', verbose_name='Attiva sito intervento'),
        ),
        migrations.AddField(
            model_name='intervento',
            name='url_committente_active',
            field=models.BooleanField(default=False, help_text='If is checked show the url commitente', verbose_name='Attiva url commitente'),
        ),
    ]
