# Generated by Django 2.0.5 on 2018-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0026_auto_20180515_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='impianti_active',
            field=models.BooleanField(default=False, help_text='If is checked show impianti', verbose_name='Attiva impianti'),
        ),
        migrations.AddField(
            model_name='intervento',
            name='impresa_active',
            field=models.BooleanField(default=False, help_text='If is checked show impresa', verbose_name='Attiva impresa'),
        ),
        migrations.AddField(
            model_name='intervento',
            name='strutture_active',
            field=models.BooleanField(default=False, help_text='If is checked show strutture', verbose_name='Attiva strutture'),
        ),
    ]
