# Generated by Django 2.0.5 on 2018-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0028_intervento_progetto_del_verde_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='commercializzazione_active',
            field=models.BooleanField(default=True, help_text='If is checked show the commercializzazione', verbose_name='Attiva commercializzazione'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='committente_active',
            field=models.BooleanField(default=True, help_text='If is checked show the committente', verbose_name='Attiva committente'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='fine_lavori_active',
            field=models.BooleanField(default=True, help_text='If is checked show the fine lavori', verbose_name='Attiva fine lavori'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='impianti_active',
            field=models.BooleanField(default=True, help_text='If is checked show impianti', verbose_name='Attiva impianti'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='impresa_active',
            field=models.BooleanField(default=True, help_text='If is checked show impresa', verbose_name='Attiva impresa'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='info_active',
            field=models.BooleanField(default=True, help_text='If is checked show the Info Project', verbose_name='Attiva Info Project'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='inizio_lavori_active',
            field=models.BooleanField(default=True, help_text='If is checked show the inizio lavori', verbose_name='Attiva inizio lavori'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='photo_active',
            field=models.BooleanField(default=True, help_text='If is checked show the Photo Album', verbose_name='Attiva Photo Album'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='progetto_del_verde_active',
            field=models.BooleanField(default=True, help_text='If is checked show progetto del verde', verbose_name='Attiva progetto del verde'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='sito_intervento_active',
            field=models.BooleanField(default=True, help_text='If is checked show sito intervento', verbose_name='Attiva sito intervento'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='strutture_active',
            field=models.BooleanField(default=True, help_text='If is checked show strutture', verbose_name='Attiva strutture'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='thumb_active',
            field=models.BooleanField(default=True, help_text='If is checked show the Thumb Project', verbose_name='Attiva Thumb Project'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='url_committente_active',
            field=models.BooleanField(default=True, help_text='If is checked show the url commitente', verbose_name='Attiva url commitente'),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='video_active',
            field=models.BooleanField(default=True, help_text='If is checked show the Video Project', verbose_name='Attiva Video Project'),
        ),
    ]
