# Generated by Django 2.0.5 on 2018-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0029_auto_20180515_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='sinonimi',
            field=models.TextField(blank=True, default=''),
        ),
    ]
