# Generated by Django 2.0.5 on 2018-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0030_intervento_sinonimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='sinonimi',
            field=models.TextField(default=''),
        ),
    ]
