# Generated by Django 2.0.5 on 2018-05-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0031_auto_20180515_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='categoria',
            field=models.CharField(choices=[('residenziale', 'Residenziale'), ('hotel', 'Hotel'), ('interni', 'Interni'), ('ristrutturazione', 'Ristrutturazione'), ('villa', 'Villa'), ('commerciale', 'Commerciale')], default='residenziale', max_length=200),
        ),
    ]
